name: Node.js Typescript CD
on:
    push:
        branches:
            - dev
            - homolog
            - prod
jobs:
    DeployToAWS:
        environment:
            name: ${{ github.ref }}
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - uses: actions/checkout@v2
            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                aws-region: sa-east-1
                role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
                role-session-name: github-action
            - name: Use Node.js 18.x
              uses: actions/setup-node@v2
              with:
                node-version: 18.x
            - name: Setting stage, stack name
              run: |
                echo "STAGE=${{ github.ref_name }}"
                echo "STACK_NAME=CleanMssTsTemplate${{ github.ref_name }}" >> $GITHUB_ENV
            - name: Install dependencies
              run: |
                yarn add vite
                yarn global add aws-cdk
                yarn install -g
                cd iac
                yarn install --frozen-lockfile            
            - name: Build and Export
              run: |
                yarn build
            - name: Setup envs
              run: |
                echo AWS_REGION=sa-east-1>> $GITHUB_ENV
                echo AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} >> $GITHUB_ENV 
                echo STACK_NAME=${{ env.STACK_NAME }} >> $GITHUB_ENV
                echo GITHUB_REF_NAME=${{ github.ref_name }} >> $GITHUB_ENV
                echo "DYNAMO_TABLE_NAME=UserMssTemplateTable" >> $GITHUB_ENV
            - name: Deploy with CDK
              run: |
                cd iac
                cdk synth
                cdk deploy --require-approval never